import { Inter } from "next/font/google";
import "./globals.css";
import { MessageProvider } from '../context/MessageContext';
import { TopicsProvider } from '../context/TopicsContext';
import { PostsProvider } from '../context/PostsContext';
// import { LeftNavProvider } from '../context/LeftNavContext';
import Nav from './components/Nav';
import ClientWrapper from './client-wrapper';
import LoginClientWrapper from './login-client-wrapper';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostsProvider>
        <MessageProvider>
          <TopicsProvider>
            <ClientWrapper>
            <LoginClientWrapper>
              {/* <div className="nav"> */}

              {/* <Nav className="nav" /> */}
              <Nav />
              {/* </div> */}
              {children}
            </LoginClientWrapper>
            </ClientWrapper>
          </TopicsProvider>
        </MessageProvider>
        </PostsProvider>
      </body>
    </html>
  );
}
